### ISSUE TITLE
Removal of container already in progress is not an error

### ISSUE THREAD

**Issue by yanjost** [Scalingo/docker-cleaner#9]
I'm being spammed by these email messages. I don't think this should be considered as an error

```
Fail to clean docker (registry-1.scalingo.com,registry-2.scalingo.com,registry-3.scalingo.com - dph-scahos01)

OUTPUT

/usr/local/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/docker-api-1.34.2/lib/docker/connection.rb:48:in `rescue in request': removal of container 5d65f6244977260cd42c17bc85c6402920489e889ee6f82bd5e06c3b192b05d4 is already in progress (Docker::Error::ConflictError)
from /usr/local/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/docker-api-1.34.2/lib/docker/connection.rb:38:in `request'
from /usr/local/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/docker-api-1.34.2/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
from /usr/local/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/docker-api-1.34.2/lib/docker/container.rb:249:in `remove'
from /opt/docker-cleaner/lib/docker_cleaner/containers.rb:10:in `remove'
from /opt/docker-cleaner/lib/docker_cleaner/containers.rb:22:in `block in run'
from /opt/docker-cleaner/lib/docker_cleaner/containers.rb:21:in `each'
from /opt/docker-cleaner/lib/docker_cleaner/containers.rb:21:in `run'
from /opt/docker-cleaner/lib/docker_cleaner.rb:6:in `run'
from /opt/docker-cleaner/bin/docker-cleaner:83:in `<top (required)>'
from /opt/docker-cleaner/binstubs/docker-cleaner:17:in `load'
from /opt/docker-cleaner/binstubs/docker-cleaner:17:in `<main>'
```

**Comment by matthieu526-scalingo** [comment]
Closing this as this is more than 3 years old, and unlikely to be done as is. I can always be reopened.
